spring.application.name=music-streaming-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/music-streaming-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Make hibernate create tables before data.sql executes
spring.jpa.defer-datasource-initialization=true
# Always execute data/schema.sql
spring.sql.init.mode=always

# Max post file size
spring.servlet.multipart.max-file-size=10MB
# Max request size
spring.servlet.multipart.max-request-size=11MB