spring.application.name=music-streaming-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/music-streaming-db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update