CREATE TABLE audio_data (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    extension   VARCHAR(255) NOT NULL,
    path        VARCHAR(255) NOT NULL,
    content_hash VARCHAR(255),
    CONSTRAINT audio_data_storage_key_key UNIQUE (storage_key)
);
